apiVersion: v1
kind: Service
metadata:
  name: datavault-app-service
  namespace: datavault
spec:
  selector:
    app: datavault-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
